# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: 13xforever.vkdiag
PackageVersion: 1.3.12
PackageLocale: en-US
Publisher: 13xforever
PackageName: VkDiag
License: MIT License
ShortDescription: VkDiag is a rudimentary vulkan diagnostics tool for Windows.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
